### ISSUE TITLE
Question about references

### ISSUE THREAD

**Issue by ApmeM** [MonoGame/MonoGame.WebDemo#2]
Hi, I have a small helper library (that do not use any other references and actually have only some math calculations) that is built using netstandart2.0 project type (as it is used in android and desktop monogame projects)

I tried to add this project to Platformer2D project but it fails with exception:
```

Could not find file '.....\bin\Debug\net472\netstandard.dll'.    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Bridge.Translator.Translator.LoadAssembly(String location, List`1 references)
   at Bridge.Translator.Translator.LoadAssembly(String location, List`1 references)
   at Bridge.Translator.Translator.LoadAssembly(String location, List`1 references)
   at Bridge.Translator.Translator.InspectReferences()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.BridgeCompilerTask.Execute()	MyONez.Samples.Web	C:\Users\usr\.nuget\packages\bridge.min\17.2.0\build\Bridge.Min.targets	25	
```

I tried to add NetStandard package from nuget but it did not help.

What should I do to be able to add some shared dll to this platformer example?

**Comment by harry-cpp** [comment]
You need to compile your library against Bridge.NET, as it does some custom patching.
